### ISSUE TITLE
@pedroprieto no consigo pasar 2 apartados del test

### ISSUE THREAD

**Issue by arantzazuGS** [arantzazuGS/practica_dwec_gestor_presupuesto#1]
@pedroprieto
Hola Pedro,
Llevo mas de 1 hora atascada y no consigo saber porque no pasa el test en 2 puntos
![image](https://user-images.githubusercontent.com/91415784/136186424-2e08779d-f565-473c-ae2e-93d11e5288fe.png)
![image](https://user-images.githubusercontent.com/91415784/136186588-848af0b3-6781-4508-aec3-af792b8b703a.png)

Puedes ayudarme?
Un saludo y gracias de antemano!!

**Comment by pedroprieto** [comment]
Buenas,

Aquí tienes que reasignar la variable, no hacer una suma:
https://github.com/arantzazuGS/practica_dwec_gestor_presupuesto/blob/313111578992cdbe84813141eead4893d5bd21c9/js/gestionPresupuesto.js#L8

(se trata de actualizar el presupuesto, no de añadir).

Y aquí, la función tiene que __devolver__ un valor, no escribirlo en la consola:
https://github.com/arantzazuGS/practica_dwec_gestor_presupuesto/blob/313111578992cdbe84813141eead4893d5bd21c9/js/gestionPresupuesto.js#L33

Un saludo!!

**Comment by arantzazuGS** [comment]
Hola Pedro,
Muchísimas gracias por las aclaraciones! Me han servido para poder finalizarla y ya te he hecho la Pull-Request
Un saludo :)

**Comment by pedroprieto** [comment]
Ya la tienes corregida. Buen trabajo!! :clap:
