### ISSUE TITLE
@pedroprieto no avanzo

### ISSUE THREAD

**Issue by arantzazuGS** [arantzazuGS/practica_dwec_gestor_presupuesto#2]
Hola Pedro,
@pedroprieto llevo desde ayer atascada en el mismo punto y no paro de dar vueltas sin conseguir solucionarlo. La parte de dentro del objeto me esta costando muchísimo implementarla. No se si podrás ayudarme con estas dudas:
- Como puedo acceder a los elementos del array etiquetas (propiedad del objeto) y operar con el? En el método del objeto actualizarEtiquetas intento añadir etiquetas nuevas al final del array con, por ejemplo: this.etiquetas.push(etiqueta), pero el test me da el error: no es una función. No se que estoy haciendo mal, quizá no se accede así a estos elementos?
- Otra parte de los test que no entiendo es, después de haber pasado el test del método  actualizarFecha() dentro del constructor, si se me ocurre tocar algo de la propiedad etiquetas (que sigue fallando), cuando lanzo el test de nuevo ya no paso actualizarFecha()
Muchas gracias de antemano por tu ayuda y disculpa las molestias!
Un saludo

Arancha

**Comment by pedroprieto** [comment]
Buenas,

El enunciado dice que `etiquetas` puede ser un número ilimitado de parámetros: esto es, no es un array, sino un parámetro Rest (https://es.javascript.info/rest-parameters-spread#parametros-rest). Por tanto, `etiquetas.length` no funcionará, porque el test está pasando un conjunto de parámetros, no un array.

En cuanto a los tests, es posible que si te da un fallo de ejecución el programa (por lo que te he comentado antes) el test se interrumpa y no ejecute el siguiente. No le des importancia.

Un saludo y ánimo!! Y nada de molestias, que para eso estamos :wink:

**Comment by arantzazuGS** [comment]
Muchas gracias Pedro! La verdad es que me había empeñado en que era un array y ahora que leo el enunciado mas detenidamente veo que tienes razón XD
Voy a intentar hacer el resto y si veo que los test no tiran te vuelvo a escribir.
Muchas gracias por tu ayuda!  =)

**Comment by arantzazuGS** [comment]
Buenas de nuevo Pedro!
He conseguido pasar el test de actualizarEtiquetas, he realizado un commit y me he puesto a tocar la propiedad etiquetas. He vuelto a lanzan el test y ha salido este error que no tengo ni idea de lo que significa ni que hacer a continución. Me he cargado algo?
![image](https://user-images.githubusercontent.com/91415784/137197341-055c7f38-8b48-459e-839c-d1dac4dd76d6.png)

**Comment by pedroprieto** [comment]
Buenas,

Es un error de sintaxis. Tienes algún fallo (un punto y coma, una llave que no cierra, etc.) en tu fichero. Utiliza un linter para depurarlo: https://www.jslint.com/

Un saludo!

**Comment by arantzazuGS** [comment]
Solucionado, muchas gracias! =)

**Comment by arantzazuGS** [comment]
Hola de nuevo Pedro!
He pasado ya 9 test y el que me falta me esta volviendo loca, porque para colmo se supone que es el mas fácil y solo muestra datos. Pues no hay manera!
Las etiquetas no entiendo porque no me muestra las 3. Y en la fecha no hay manera de que salga "00" segundos.
 Te pego el código a ver si me puedes arrojar algo de luz porfa:
Esto es lo que sale en el test:
![image](https://user-images.githubusercontent.com/91415784/137308813-ebcf9967-3f9e-4ef6-ad8a-9b9e4a571ce7.png)
Y esta la parte del código:
![image](https://user-images.githubusercontent.com/91415784/137308936-049575bf-abca-4eea-8a67-c4fac815f4fc.png)
Un saludo y muchas gracias por toda tu ayuda :)

**Comment by pedroprieto** [comment]
Buenas,

La fecha no la tienes que sacar así. Usa el método que pone en el enunciado.

Las etiquetas salen todas. Únicamente la primera no sale en línea nueva.

Ánimo, que casi está!!

**Comment by arantzazuGS** [comment]
Gracias Pedro, ya lo he modificado pero sigue sin pasar el test. De todos modos te he hecho la pull request porque tampoco te quiero molestar mas. Pero ya por curiosidad, aunque no puntue, que estoy haciendo mal?
![image](https://user-images.githubusercontent.com/91415784/137337334-146d09d3-dd78-4a2f-8256-e7bdb3a839c7.png)
![image](https://user-images.githubusercontent.com/91415784/137337396-e7991680-4d4a-40d8-9f42-d0dc4656c750.png)

**Comment by pedroprieto** [comment]
Buenas,

No molestas en absoluto. Las dudas dudas son :smiley: 

Te contesto en la PR, que puedo comentar sobre código.

**Comment by arantzazuGS** [comment]
Muchas gracias Pedro. Es que me sabe mal porque al final me vas a hacer tu el ejercicio 😄 
Ya lo tengo todo verde, que alegría!
te mando pull request
Mil gracias de nuevo!!

**Comment by arantzazuGS** [comment]
Pedro te escribo de nuevo porque veo que en actions sigue saliendome el aspa roja despues de subir los cambios, aunque por consola me salen todos los test verdes:
![image](https://user-images.githubusercontent.com/91415784/137467697-25503a83-7bc7-4ad2-ae10-a0059b3d814f.png)
![image](https://user-images.githubusercontent.com/91415784/137467742-b6613224-59a6-40f2-b148-3303a6cbe2d4.png)

**Comment by pedroprieto** [comment]
Acabo de ponerte un comentario: en GitHub, la localización es de un servidor inglés. Por eso no coincide el formato de fecha con el de tu ordenador. Te he puesto el comentario en la PR.

**Comment by arantzazuGS** [comment]
Hecho! 👍

**Comment by arantzazuGS** [comment]
El error se reflejaba en alguna parte? Por si me vuelve a pasar algo parecido, saber donde tengo que mirar.

**Comment by pedroprieto** [comment]
Solo al ejecutar el test en GitHub.

**Comment by arantzazuGS** [comment]
Perfecto, muchas gracias. Estaré atenta en la próxima practica por si me vuelve a pasar. Cierro ya esta Issue.
Buen finde!
un saludo 😄
